### ISSUE TITLE
Rename identifiers that are reserved keywords in Rust

### ISSUE THREAD

**Issue by virtualritz** [konchunas/pyrs#11]
I suggest doing what `bindgen` does and just adding an underscore:
`struct -> struct_`
`type -> type_`

**Comment by konchunas** [comment]
Thank you, nice suggestion!
Implemented in [this commit](https://github.com/konchunas/pyrs/commit/261e63b619df5c4ae06616b1ced2e0ef5fb0d26f)

But I wouldn't recommend using `type` as a variable name :)

**Comment by virtualritz** [comment]
Nice. But seems rather short. Shouldn't this include everything from [here](https://doc.rust-lang.org/reference/keywords.html#strict-keywords)?

**Comment by konchunas** [comment]
Basically it should.
I tried to include everything allowed in Python, but forbidden in Rust.
Some keywords like `async` are forbidden to be used as variable names in Python as well, so I decided to omit them.
I haven't touched reserved Rust keywords though.
