### ISSUE TITLE
PyPI conflict

### ISSUE THREAD

**Issue by jayvdb** [konchunas/pyrs#16]
setup.py uses name 'pyrs', but https://pypi.org/project/pyrs/ is already taken.

[`python-rs`](https://pypi.org/project/python-rs/) is available.

It would be great to see this on PyPI, even in alpha/pre-release status.

**Comment by jayvdb** [comment]
ping @konchunas

**Comment by jayvdb** [comment]
https://pypi.org/project/py2rs/ is also available.

**Comment by konchunas** [comment]
Hey, @jayvdb.
I think `python-rs` is nice, lets use that.
Could you make a pull request for that?

**Comment by jayvdb** [comment]
I'd be happy to do that after https://github.com/konchunas/pyrs/pull/19 which is needed to prep it for installation via pip.

**Comment by jayvdb** [comment]
@konchunas , would you now cut a release and upload to PyPI, otherwise someone else soon will also use `python-rs`

**Comment by konchunas** [comment]
Done at https://pypi.org/project/python-rs/0.1.0/
