### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by adsharma** [konchunas/pyrs#17]
```
$ cd pyrs/pyrs; pytest-3
```

Gives me:

> 6 failed, 27 passed 

What do you think about restoring the py14 code and the tests, so we can have one tree where both C++ and Rust are functional along with passing tests?

**Comment by adsharma** [comment]
https://github.com/konchunas/pyrs/pull/18

**Comment by konchunas** [comment]
I think tests are good, but I don't see any benefit of having C++ tests in this project. This is Rust-only transpiler and having it doing only one language makes code more concise and readable.
What are you trying to achieve here?

**Comment by adsharma** [comment]
The way the code is structured is already a clike base class and per
language quirks. Looks like you have maintained that structure. If you want
to make it rust only (which I would not recommend) a different code
structure may make more sense.

Having some aututomated tests is my top level objective. Not breaking C++
and perhaps supporting other clike languages (I've been thinking Julia -
just for kix) is another objective.

Also related:

https://adsharma.github.io/python-622/

**Comment by adsharma** [comment]
Reorganized code a bit with tests passing here.
Credited your work as well as upstream py14.

https://github.com/adsharma/py2many
